/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author ASUS
 */
public class Fbill extends javax.swing.JPanel {

    public Fbill() {
        initComponents();
        this.setSize(790, 630);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 153, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        setPreferredSize(new java.awt.Dimension(790, 630));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Chọn sách");
        add(jLabel2);
        jLabel2.setBounds(350, 250, 90, 25);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã sách", "Tên", "Thể loại", "Tác giả", "Số lượng", "Đơn giá nhập", "Đơn giá bán"
            }
        ));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMaxWidth(45);
            jTable2.getColumnModel().getColumn(1).setMaxWidth(60);
            jTable2.getColumnModel().getColumn(5).setMaxWidth(60);
        }

        add(jScrollPane2);
        jScrollPane2.setBounds(0, 390, 790, 240);

        jLabel14.setText("Khách hàng");
        add(jLabel14);
        jLabel14.setBounds(10, 55, 130, 20);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox5);
        jComboBox5.setBounds(80, 50, 270, 29);

        jLabel15.setText("Ngày hóa đơn");
        add(jLabel15);
        jLabel15.setBounds(10, 98, 350, 13);

        jTextField8.setEditable(false);
        add(jTextField8);
        jTextField8.setBounds(80, 90, 270, 29);

        jLabel16.setText("Tổng tiền");
        add(jLabel16);
        jLabel16.setBounds(10, 138, 60, 13);

        jTextField9.setEditable(false);
        add(jTextField9);
        jTextField9.setBounds(80, 130, 270, 29);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setText("Danh sách sách mua");
        add(jLabel1);
        jLabel1.setBounds(530, 30, 110, 13);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã", "Tên", "Đơn giá", "SL", "Thành tiền"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(35);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(35);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(35);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(370, 50, 410, 170);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Hóa đơn");
        add(jLabel3);
        jLabel3.setBounds(346, 0, 98, 32);

        jLabel4.setText("Số lượng");
        add(jLabel4);
        jLabel4.setBounds(630, 300, 50, 13);
        add(jTextField1);
        jTextField1.setBounds(690, 290, 90, 29);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/billAdd.png"))); // NOI18N
        add(jButton1);
        jButton1.setBounds(300, 170, 50, 50);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bookAdd.png"))); // NOI18N
        add(jButton2);
        jButton2.setBounds(730, 330, 50, 50);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox2);
        jComboBox2.setBounds(420, 290, 200, 29);

        jComboBox3.setEditable(true);
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox3);
        jComboBox3.setBounds(80, 340, 270, 29);
        add(jTextField2);
        jTextField2.setBounds(80, 290, 270, 29);

        jLabel5.setText("Tên sách");
        add(jLabel5);
        jLabel5.setBounds(10, 300, 50, 13);

        jLabel6.setText("Tác giả");
        add(jLabel6);
        jLabel6.setBounds(10, 350, 50, 13);

        jLabel7.setText("Thể loại");
        add(jLabel7);
        jLabel7.setBounds(370, 300, 120, 13);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bookSearch.png"))); // NOI18N
        add(jButton3);
        jButton3.setBounds(420, 330, 50, 50);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bookDel.png"))); // NOI18N
        add(jButton4);
        jButton4.setBounds(730, 230, 50, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Bill_Background.jpg"))); // NOI18N
        add(jLabel8);
        jLabel8.setBounds(0, 0, 790, 630);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
