/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author ASUS
 */
public class FBookInventory extends javax.swing.JPanel {

    /**
     * Creates new form FBookCategory
     */
    public FBookInventory() {
        initComponents();
        this.setSize(790, 630);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(790, 630));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông tin sách");
        add(jLabel1);
        jLabel1.setBounds(311, 5, 168, 32);
        add(jTextField1);
        jTextField1.setBounds(70, 60, 270, 28);

        jLabel3.setText("Tên sách");
        add(jLabel3);
        jLabel3.setBounds(20, 68, 60, 13);

        jComboBox1.setEditable(true);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1);
        jComboBox1.setBounds(70, 100, 270, 28);

        jLabel2.setText("Thể loại");
        add(jLabel2);
        jLabel2.setBounds(20, 108, 50, 13);

        jLabel4.setText("Tác giả");
        add(jLabel4);
        jLabel4.setBounds(350, 68, 40, 13);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã", "Tên sách", "Thể loại", "Tác giả", "SL", "ĐG Nhập", "ĐG Bán"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(35);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(35);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(35);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 189, 790, 440);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bookUpd.png"))); // NOI18N
        add(jButton2);
        jButton2.setBounds(730, 80, 35, 35);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.png"))); // NOI18N
        add(jButton3);
        jButton3.setBounds(730, 130, 35, 35);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bookSearch.png"))); // NOI18N
        add(jButton5);
        jButton5.setBounds(730, 30, 35, 35);

        jComboBox2.setEditable(true);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox2);
        jComboBox2.setBounds(420, 60, 270, 29);

        jLabel5.setText("Đơn giá nhập");
        add(jLabel5);
        jLabel5.setBounds(350, 108, 80, 13);
        add(jSpinner1);
        jSpinner1.setBounds(420, 100, 270, 29);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Book_Background.jpg"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(0, 0, 790, 630);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
