/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author ASUS
 */
public class FBookReceive extends javax.swing.JPanel {

    /**
     * Creates new form FBookReceive
     */
    public FBookReceive() {
        initComponents();
        this.setSize(790, 630);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 102));
        setPreferredSize(new java.awt.Dimension(790, 630));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Phiếu nhập sách");
        add(jLabel1);
        jLabel1.setBounds(302, 2, 185, 32);

        jLabel2.setText("Mã sách");
        add(jLabel2);
        jLabel2.setBounds(210, 58, 50, 13);

        jComboBox1.setEditable(true);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1);
        jComboBox1.setBounds(260, 90, 330, 28);

        jLabel3.setText("Tên sách");
        add(jLabel3);
        jLabel3.setBounds(210, 97, 50, 13);

        jTextField1.setEditable(false);
        add(jTextField1);
        jTextField1.setBounds(260, 50, 330, 29);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox2);
        jComboBox2.setBounds(260, 130, 132, 29);

        jLabel4.setText("Thể loại");
        add(jLabel4);
        jLabel4.setBounds(210, 138, 50, 13);

        jLabel5.setText("Tác giả");
        add(jLabel5);
        jLabel5.setBounds(400, 138, 40, 13);

        jLabel6.setText("Số lượng");
        add(jLabel6);
        jLabel6.setBounds(210, 178, 50, 13);
        add(jTextField3);
        jTextField3.setBounds(260, 170, 88, 29);

        jLabel7.setText("Đơn giá nhập");
        add(jLabel7);
        jLabel7.setBounds(360, 178, 70, 13);
        add(jTextField4);
        jTextField4.setBounds(440, 170, 150, 29);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bookAdd.png"))); // NOI18N
        add(jButton4);
        jButton4.setBounds(420, 210, 50, 50);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bookUpd.png"))); // NOI18N
        add(jButton5);
        jButton5.setBounds(480, 210, 50, 50);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bookDel.png"))); // NOI18N
        add(jButton6);
        jButton6.setBounds(540, 210, 50, 50);

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Sách mới ?");
        jCheckBox1.setOpaque(false);
        add(jCheckBox1);
        jCheckBox1.setBounds(260, 225, 100, 21);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã", "Tên sách", "Thể loại", "Tác giả", "SL", "Đơn giá", "Thành tiền"
            }
        ));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMaxWidth(40);
            jTable2.getColumnModel().getColumn(1).setMaxWidth(40);
            jTable2.getColumnModel().getColumn(5).setMaxWidth(40);
        }

        add(jScrollPane2);
        jScrollPane2.setBounds(0, 340, 790, 290);

        jTextField5.setEditable(false);
        add(jTextField5);
        jTextField5.setBounds(570, 290, 136, 29);

        jLabel8.setText("Tổng tiền");
        add(jLabel8);
        jLabel8.setBounds(510, 298, 60, 13);

        jComboBox3.setEditable(true);
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox3);
        jComboBox3.setBounds(440, 130, 150, 29);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Danh sách sách nhập");
        add(jLabel13);
        jLabel13.setBounds(305, 290, 180, 25);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/importAdd.png"))); // NOI18N
        add(jButton1);
        jButton1.setBounds(730, 280, 50, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Import_Background.jpg"))); // NOI18N
        add(jLabel9);
        jLabel9.setBounds(0, 0, 790, 630);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
