/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author ASUS
 */
public class FCashReceive extends javax.swing.JPanel {

    /**
     * Creates new form FCashReceive
     */
    public FCashReceive() {
        initComponents();
        this.setSize(790, 630);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 0));
        setPreferredSize(new java.awt.Dimension(790, 630));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Lập phiếu thu tiền");
        add(jLabel1);
        jLabel1.setBounds(291, 0, 207, 32);

        jLabel6.setText("Khách hàng");
        add(jLabel6);
        jLabel6.setBounds(180, 60, 60, 13);

        jComboBox2.setEditable(true);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox2);
        jComboBox2.setBounds(240, 50, 340, 29);
        add(jTextField4);
        jTextField4.setBounds(440, 100, 140, 29);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/paymentAdd.png"))); // NOI18N
        add(jButton1);
        jButton1.setBounds(370, 140, 50, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã HĐ", "Khách hàng", "Ngày HĐ", "Giá trị", "Trạng thái"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(45);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(45);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 200, 790, 430);

        jLabel11.setText("Nợ");
        add(jLabel11);
        jLabel11.setBounds(180, 107, 30, 13);

        jTextField8.setEditable(false);
        add(jTextField8);
        jTextField8.setBounds(240, 100, 140, 29);

        jLabel12.setText("Tiền thu");
        add(jLabel12);
        jLabel12.setBounds(390, 108, 50, 13);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Payment_Background.jpg"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 0, 790, 630);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
