/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author ASUS
 */
public class FCustomer extends javax.swing.JPanel {

    /**
     * Creates new form FCustomer
     */
    public FCustomer() {
        initComponents();
        this.setSize(790,630);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(790, 552));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Quản lý khách hàng");
        add(jLabel2);
        jLabel2.setBounds(282, 5, 225, 32);

        jLabel3.setText("Họ, tên");
        add(jLabel3);
        jLabel3.setBounds(10, 59, 50, 13);
        add(jTextField1);
        jTextField1.setBounds(60, 50, 370, 29);

        jLabel4.setText("Địa chỉ");
        add(jLabel4);
        jLabel4.setBounds(10, 98, 40, 13);
        add(jTextField2);
        jTextField2.setBounds(60, 90, 580, 29);

        jLabel5.setText("SĐT");
        add(jLabel5);
        jLabel5.setBounds(440, 59, 30, 13);
        add(jTextField3);
        jTextField3.setBounds(470, 50, 170, 29);

        jLabel6.setText("Email");
        add(jLabel6);
        jLabel6.setBounds(10, 138, 50, 13);
        add(jTextField4);
        jTextField4.setBounds(60, 130, 370, 29);

        jLabel7.setText("Nợ");
        add(jLabel7);
        jLabel7.setBounds(440, 138, 30, 13);

        jTextField5.setEditable(false);
        add(jTextField5);
        jTextField5.setBounds(470, 130, 170, 29);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/customerAdd.png"))); // NOI18N
        add(jButton1);
        jButton1.setBounds(660, 50, 50, 50);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/customerUpd.png"))); // NOI18N
        add(jButton2);
        jButton2.setBounds(660, 110, 50, 50);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/customerDel.png"))); // NOI18N
        add(jButton3);
        jButton3.setBounds(720, 50, 50, 50);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/customerSearch.png"))); // NOI18N
        add(jButton4);
        jButton4.setBounds(720, 110, 50, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã KH", "Họ, tên", "SĐT", "Email", "Địa chỉ", "Nợ"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(40);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(50);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(-2, 175, 796, 400);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Customer_Background.jpg"))); // NOI18N
        add(jLabel9);
        jLabel9.setBounds(0, -10, 790, 390);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
