/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author ASUS
 */
public class FReportRevenue extends javax.swing.JPanel {

    /**
     * Creates new form FReportRevenue
     */
    public FReportRevenue() {
        initComponents();
        this.setSize(790, 630);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Báo cáo công nợ");
        add(jLabel1);
        jLabel1.setBounds(300, 0, 191, 32);

        jLabel2.setText("Tháng");
        add(jLabel2);
        jLabel2.setBounds(290, 50, 40, 13);

        jLabel3.setText("Năm");
        add(jLabel3);
        jLabel3.setBounds(400, 50, 30, 13);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã", "Họ, tên", "Nợ đầu", "Phát sinh", "Nợ cuối"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(45);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(45);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 162, 790, 470);

        jLabel4.setText("Lọc theo: ");
        add(jLabel4);
        jLabel4.setBounds(190, 88, 46, 13);

        jLabel5.setText("Khách hàng");
        add(jLabel5);
        jLabel5.setBounds(250, 88, 70, 13);

        jComboBox2.setEditable(true);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox2);
        jComboBox2.setBounds(320, 80, 280, 29);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/reportAdd.png"))); // NOI18N
        add(jButton1);
        jButton1.setBounds(378, 118, 35, 35);
        add(jSpinner2);
        jSpinner2.setBounds(430, 40, 70, 29);
        add(jSpinner1);
        jSpinner1.setBounds(330, 40, 50, 29);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Rev_Background.jpg"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(0, 0, 790, 630);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
