/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.AccountController;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
/**
 *
 * @author ASUS
 */
public class FStaff extends javax.swing.JPanel {

    AccountController controller = new AccountController();
    public FStaff() {
        initComponents();
        this.setSize(790, 630);
        Table_Account.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        Table_Account.getTableHeader().setOpaque(true);
        Table_Account.getTableHeader().setBackground(new Color(30,136,203));
        Table_Account.getTableHeader().setForeground(new Color(0,0,255));
        Table_Account.setRowHeight(25);
        ShowDataOn_Info_Panel();
    }
    
        private void ShowDataOn_Info_Panel(){
        int row = Table_Account.getSelectedRow();
        if(row!=-1){
            //if row is selected
            String username = String.valueOf(Table_Account.getValueAt(row, 2));
            Info_address.setText(controller.getAccountByUsername(username).getAddress());
            Info_email.setText(controller.getAccountByUsername(username).getEmail());
            Info_pass.setText(controller.getAccountByUsername(username).getPassword());
            Info_phone.setText(controller.getAccountByUsername(username).getPhoneNumber());
            Info_realname.setText(controller.getAccountByUsername(username).getRealName());
            Info_username.setText(controller.getAccountByUsername(username).getUsername());
            int type = controller.getAccountByUsername(username).getType();
            if(type==0){
                //when user is admin
                Info_type.setSelectedItem("0: Admin");
                
            } else
                Info_type.setSelectedItem("1: Nhân viên");
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Info = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Info_username = new javax.swing.JTextField();
        Info_pass = new javax.swing.JTextField();
        Info_realname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Info_address = new javax.swing.JTextField();
        Info_email = new javax.swing.JTextField();
        Info_phone = new javax.swing.JTextField();
        Info_type = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Label_Background = new javax.swing.JLabel();
        List_Panel = new javax.swing.JScrollPane();
        Table_Account = new javax.swing.JTable();
        Button_Add = new javax.swing.JButton();
        Button_Update = new javax.swing.JButton();
        Button_Delete = new javax.swing.JButton();
        Button_Refresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(790, 630));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Info.setBackground(new java.awt.Color(255, 255, 153));
        Panel_Info.setFocusable(false);
        Panel_Info.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Username");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Panel_Info.add(jLabel1);
        jLabel1.setBounds(60, 50, 66, 30);

        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Password");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Panel_Info.add(jLabel2);
        jLabel2.setBounds(60, 90, 66, 26);

        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Real Name");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Panel_Info.add(jLabel3);
        jLabel3.setBounds(60, 130, 66, 30);
        Panel_Info.add(Info_username);
        Info_username.setBounds(130, 50, 224, 30);
        Panel_Info.add(Info_pass);
        Info_pass.setBounds(130, 90, 224, 30);
        Panel_Info.add(Info_realname);
        Info_realname.setBounds(130, 130, 224, 30);

        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Địa chỉ");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Panel_Info.add(jLabel5);
        jLabel5.setBounds(440, 50, 50, 30);

        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Email");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Panel_Info.add(jLabel6);
        jLabel6.setBounds(440, 90, 50, 30);

        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("SĐT");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Panel_Info.add(jLabel7);
        jLabel7.setBounds(460, 130, 30, 24);
        Panel_Info.add(Info_address);
        Info_address.setBounds(500, 50, 248, 30);
        Panel_Info.add(Info_email);
        Info_email.setBounds(500, 90, 248, 30);
        Panel_Info.add(Info_phone);
        Info_phone.setBounds(500, 130, 130, 30);

        Info_type.setBackground(new java.awt.Color(204, 204, 255));
        Info_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--type--", "0: Admin", "1: Nhân viên",}));
        Info_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Info_typeActionPerformed(evt);
            }
        });
        Panel_Info.add(Info_type);
        Info_type.setBounds(640, 130, 110, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Thông tin chi tiết");
        Panel_Info.add(jLabel4);
        jLabel4.setBounds(40, 0, 700, 44);

        Label_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Customer_Background.jpg"))); // NOI18N
        Panel_Info.add(Label_Background);
        Label_Background.setBounds(0, 0, 790, 180);

        add(Panel_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 173));

        List_Panel.setBackground(new java.awt.Color(255, 255, 255));
        List_Panel.setBorder(null);
        List_Panel.setHorizontalScrollBar(null);

        Table_Account.setFont(new java.awt.Font("Segoe UI", 0, 18));
        Table_Account.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên nhân viên", "Tên tài khoản", "Loại tài khoản"
            }
        ));
        Table_Account.setToolTipText("");
        Table_Account.setGridColor(new java.awt.Color(255, 255, 255));
        Table_Account.setName(""); // NOI18N
        Table_Account.setOpaque(false);
        Table_Account.setRowHeight(25);
        Table_Account.setSelectionBackground(new java.awt.Color(232, 57, 95));
        Table_Account.setShowHorizontalLines(true);
        Table_Account.getTableHeader().setReorderingAllowed(false);
        Table_Account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_AccountMouseClicked(evt);
            }
        });
        List_Panel.setViewportView(Table_Account);

        add(List_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 790, 410));

        Button_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/customerAdd.png"))); // NOI18N
        Button_Add.setText("Thêm");
        Button_Add.setPreferredSize(new java.awt.Dimension(84, 36));
        Button_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AddActionPerformed(evt);
            }
        });
        add(Button_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, 100, 30));

        Button_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/customerUpd.png"))); // NOI18N
        Button_Update.setText("Sửa");
        Button_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_UpdateActionPerformed(evt);
            }
        });
        add(Button_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 590, 90, 30));

        Button_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.png"))); // NOI18N
        Button_Delete.setText("Xóa");
        Button_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DeleteActionPerformed(evt);
            }
        });
        add(Button_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 590, 90, 30));

        Button_Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        Button_Refresh.setText("refresh");
        Button_Refresh.setPreferredSize(new java.awt.Dimension(84, 36));
        Button_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RefreshActionPerformed(evt);
            }
        });
        add(Button_Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 590, 100, 30));
    }// </editor-fold>//GEN-END:initComponents


    private void Button_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AddActionPerformed
        String username = Info_username.getText();
        String pass = Info_pass.getText();
        String email = Info_email.getText();
        String phone = Info_phone.getText();
        int type;
        String TypeInCombobox = (String)Info_type.getSelectedItem();
        if(TypeInCombobox.equals("0: Admin"))
            type=0;
        else
            type=1;
        String name  = Info_realname.getText();
        String addre = Info_address.getText();
        if(controller.AddAccount(username, pass, type, name, phone, email, addre))
        {
            JOptionPane.showMessageDialog(null, "Thêm account thành công !");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Thêm account thất bại !");
        }
        controller.getAccount(Table_Account);
    }//GEN-LAST:event_Button_AddActionPerformed

    private void Button_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RefreshActionPerformed
        controller.getAccount(Table_Account);
        Info_address.setText("");
        Info_email.setText("");
        Info_username.setText("");
        Info_pass.setText("");
        Info_phone.setText("");
        Info_realname.setText("");
    }//GEN-LAST:event_Button_RefreshActionPerformed

    private void Table_AccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_AccountMouseClicked
        ShowDataOn_Info_Panel();
    }//GEN-LAST:event_Table_AccountMouseClicked

    private void Button_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DeleteActionPerformed
        String username = Info_username.getText();
        if(controller.DeleteAccountByUsername(username))
        {
            JOptionPane.showMessageDialog(null, "Xóa account thành công !");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Xóa account thất bại !");
        }
        controller.getAccount(Table_Account);
    }//GEN-LAST:event_Button_DeleteActionPerformed

    private void Button_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_UpdateActionPerformed
        String username = Info_username.getText();
        String pass = Info_pass.getText();
        String email = Info_email.getText();
        String phone = Info_phone.getText();
        int type;
        String TypeInCombobox = (String)Info_type.getSelectedItem();
        if(TypeInCombobox.equals("0: Admin"))
            type=0;
        else
            type=1;
        String name  = Info_realname.getText();
        String addre = Info_address.getText();
        if(controller.UpdateAccountByUsername(username, pass, type, name, phone, email, addre))
        {
            JOptionPane.showMessageDialog(null, "Sửa account thành công !");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Sửa account thất bại !");
        }
        controller.getAccount(Table_Account);
    }//GEN-LAST:event_Button_UpdateActionPerformed

    private void Info_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Info_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Info_typeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Add;
    private javax.swing.JButton Button_Delete;
    private javax.swing.JButton Button_Refresh;
    private javax.swing.JButton Button_Update;
    private javax.swing.JTextField Info_address;
    private javax.swing.JTextField Info_email;
    private javax.swing.JTextField Info_pass;
    private javax.swing.JTextField Info_phone;
    private javax.swing.JTextField Info_realname;
    private javax.swing.JComboBox<String> Info_type;
    private javax.swing.JTextField Info_username;
    private javax.swing.JLabel Label_Background;
    private javax.swing.JScrollPane List_Panel;
    private javax.swing.JPanel Panel_Info;
    private javax.swing.JTable Table_Account;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
