/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author ASUS
 */
public class FWelcome extends javax.swing.JPanel {

    /**
     * Creates new form FWelcome
     */
    public FWelcome() {
        this.setSize(790, 630);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Head = new javax.swing.JLabel();
        Label_Background = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Head.setBackground(new java.awt.Color(204, 102, 255));
        Label_Head.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Label_Head.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Head.setText("WELCOME ");
        Label_Head.setOpaque(true);
        add(Label_Head, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 380, 70));

        Label_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Main_Background.jpg"))); // NOI18N
        add(Label_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Background;
    private javax.swing.JLabel Label_Head;
    // End of variables declaration//GEN-END:variables
}
